language: c

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq build-essential curl; fi

script:
    - echo 'America/Los_Angeles' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - DIRECTINSTALL=yes ./1-BasicSetUp.sh
    - DIRECTINSTALL=yes ./2-GenSoftware.sh
    - DIRECTINSTALL=yes ./opencvDirectInstall.sh
    - ./ML-Basic.sh